

# This file was *autogenerated* from the file gen_prime.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
from argparse import ArgumentParser
parser=ArgumentParser()

parser.add_argument('-v','--verbose',action='store_true')
parser.add_argument('-n','--nbprimes', default='14')

args=parser.parse_args()
nb_primes=Integer(args.nbprimes)

cond_file="../../txt/conductor_"+str(nb_primes)+"_primes.md"
F=open(cond_file, "r")
F.readline()

f=Integer(F.readline())

F.close()
primes=[]
p=_sage_const_5 
i=_sage_const_0 
while i<nb_primes:
	if p&_sage_const_3 ==_sage_const_1 :
		primes.append(p)
		i+=_sage_const_1 
	p=p.next_prime()


L1=prod(primes[_sage_const_1 :])
L2=_sage_const_5 
L=L1*L2

p=L-_sage_const_1 
c=_sage_const_1 
pmone=_sage_const_1 

if args.verbose:
	print(f"Generating characteristic for conductor {f} with norm {L} and primes {primes}\n")
while True:
	p=c*L-_sage_const_1 
	if p.is_pseudoprime() and p&_sage_const_3 ==_sage_const_3 :
		pmone=-_sage_const_1 
		break
	p=p+_sage_const_2 
	if p.is_pseudoprime() and p&_sage_const_3 ==_sage_const_3 :
		pmone=_sage_const_1 
		break
	c+=_sage_const_1 

if args.verbose:
	if p in Primes():
		print(f"Found prime {p} with c={c} and p=cL+({pmone})\n")
	else:
		print("Pseudo-primality test failed\n")
		raise ValueError

filename="../../txt/prime_"+str(nb_primes)+"_primes.md"
if args.verbose:
	print(f"Storing prime {p} in file {filename}")

G=open(filename,"w")
G.write(f"{p}\n{c}\n{pmone}")
G.close()

