

# This file was *autogenerated* from the file find_prime.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
from argparse import ArgumentParser
parser=ArgumentParser()

parser.add_argument('-c','--conductor')
parser.add_argument('-n','--nbprimes')

args=parser.parse_args()

conductor=Integer(args.conductor)
nb_primes=Integer(args.nbprimes)


filename="../candidate_conductors/candidate_conductors"+str(nb_primes)+".md"
g=open(filename, "r")
line=_sage_const_0 

nim=abs(Integer(g.readline().split(" ")[_sage_const_0 ]))
nre=abs(Integer(g.readline().split(" ")[_sage_const_0 ]))

while nim!=conductor and nre!=conductor:
	nim=abs(Integer(g.readline().split(" ")[_sage_const_0 ]))
	nre=abs(Integer(g.readline().split(" ")[_sage_const_0 ]))
	line+=_sage_const_2 

print(line)
print(conductor,nim, nre)

