

# This file was *autogenerated* from the file find_prime.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
filename="../../txt/conductor_80_bits.md"

f=open(filename, "r")
f.readline()

conductor=Integer(f.readline())

f.close()

filename="../ideals/candidate_conductors16.md"
g=open(filename, "r")
line=_sage_const_0 

n=abs(Integer(g.readline().split(" ")[_sage_const_0 ]))

while n!=conductor:
	n=abs(Integer(g.readline().split(" ")[_sage_const_0 ]))
	line+=_sage_const_1 

print(line)
print(conductor,n)

