

# This file was *autogenerated* from the file gen_primes_and_sqrts.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3)
from sage.rings.finite_rings.integer_mod import square_root_mod_prime
from argparse import ArgumentParser
parser = ArgumentParser()

parser.add_argument('-v', '--verbose', action='store_true')
parser.add_argument('-n', '--nbprimes', default='14')

args = parser.parse_args()

nb_primes=Integer(args.nbprimes)

K = NumberField(x**_sage_const_2 +_sage_const_1 , names=('i',)); (i,) = K._first_ngens(1)
primes=[]
p=_sage_const_5 
i=_sage_const_0 
while i<nb_primes:
	if p&_sage_const_3 ==_sage_const_1 :
		primes.append(p)
		i+=_sage_const_1 
	p=p.next_prime()

if args.verbose:
	print(f"Computing roots of -1 modulo the first {nb_primes}-primes\n")

sqrts=[square_root_mod_prime(Mod(-_sage_const_1 ,i), p=i) for i in primes]
if args.verbose:
	for i in range(nb_primes):
		print(f"{sqrts[i]}**2=-1 mod {primes[i]}\n")


filename="../../txt/sqrts_"+str(nb_primes)+"_primes.md"

f=open(filename, "w")

if args.verbose:
	print(f"Writing to file {filename}\n")

f.write(f"{nb_primes}\n")
for i in range(nb_primes):
	f.write(f"{sqrts[i]}\n")

f.close()

